version: '3'
services:
  cms-db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mySecretPassw0rd
      - MYSQL_DATABASE=std_services
  php-fpm:
    build:
      context: . 
      dockerfile: ./php/Dockerfile
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      - cms-db
      - php-fpm
