version: '3'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=zx6PDeOtvapS7rv7
    volumes:
      - "./var/mariadb/data:/var/lib/mysql"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "38080:8080"
  
  php-fpm:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/usr/share/nginx/html
  
  app:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cms-db
      - php-fpm
    volumes:
      - ./app:/usr/share/nginx/html
